title: Freivin Campbell

description: Blog sobre contenido WEB, amante de la programación.
logo: https://avatars1.githubusercontent.com/u/7534967?v=3&s=200
author: Freivin Campbell


baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
paginate: 5
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji

gist:
  noscript: false

navigation:
 - title: Home
   url: /index.html
 - title: Todos los artículos
   url: /articles
 # - title: Contact
 #   url: /contact

social:
   github: Freivincampbell
   instagram: freivincampbell
   twitter: freivin12
   facebook: Freivincampbell
   email: freivin12@gmail.com



google_analytics: "UA-77785423-2"

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
